minVersion: 0.34.1
targets:
  - name: pypi
    includeNames: /^debugg-ai[_\-]sdk.*$/
  - name: gh-pages
  - name: registry
    sdks:
      pypi:debugg-ai-sdk:
  - name: github
  - name: aws-lambda-layer
    # This regex that matches the version is taken from craft:
    # https://github.com/debugg-ai/craft/blob/8d77c38ddbe4be59f98f61b6e42952ca087d3acd/src/utils/version.ts#L11
    includeNames: /^debugg-ai-py-serverless-\bv?(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(?:-?([\da-z-]+(?:\.[\da-z-]+)*))?(?:\+([\da-z-]+(?:\.[\da-z-]+)*))?\b.zip$/
    layerName: DebuggAIPythonServerlessSDK
    compatibleRuntimes:
      - name: python
        versions:
          # The number of versions must be, at most, the maximum number of
          # runtimes AWS Lambda permits for a layer (currently 15).
          # On the other hand, AWS Lambda does not support every Python runtime.
          # The supported runtimes are available in the following link:
          # https://docs.aws.amazon.com/lambda/latest/dg/lambda-python.html
          - python3.7
          - python3.8
          - python3.9
          - python3.10
          - python3.11
          - python3.12
          - python3.13
    license: MIT
  - name: debugg-ai-pypi
    internalPypiRepo: debugg-ai/pypi
changelog: CHANGELOG.md
changelogPolicy: auto
