AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  DebuggAILambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_deployment_package.zip
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Timeout: 30
      Environment:
        Variables:
          DEBUGGAI_INGEST_URL: !Ref DebuggAIDsn
      Events:
        ApiEventGet:
          Type: Api
          Properties:
            Path: /
            Method: get
        ApiEventPost:
          Type: Api
          Properties:
            Path: /
            Method: post

Parameters:
  DebuggAIDsn:
    Type: String
    Default: ''
